/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Alumne_controller;
import controlador.Cicle_controller;
import controlador.Curs_Controller;
import controlador.Familia_controller;
import controlador.Modul_controller;
import controlador.UnitatFormativa_controller;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.NoResultException;
import javax.persistence.PersistenceException;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import model.Alumne;
import model.Cicle;
import model.Curs;
import model.Curs.Nom;
import model.Familia;
import model.Modul;
import model.UnitatFormativa;

/**
 *
 * @author ALUMNEDAM
 */
public class GUI extends javax.swing.JFrame {

    public GUI() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableCicle = new javax.swing.JTable();
        idCicle = new javax.swing.JTextField();
        nomCicle = new javax.swing.JTextField();
        btnAfegirCicle = new javax.swing.JButton();
        btnCercarTotsCicle = new javax.swing.JButton();
        btnModificarCicle = new javax.swing.JButton();
        btnEliminarCicle = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        familiaCicle = new javax.swing.JTextField();
        grauCicle = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        idCurs = new javax.swing.JTextField();
        btnAfegirCurs = new javax.swing.JButton();
        btnCercarTotsCurs = new javax.swing.JButton();
        btnEliminarCurs = new javax.swing.JButton();
        btnModificarCurs = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaCurs = new javax.swing.JTable();
        nomCurs = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        cicleCurs = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        idFamilia = new javax.swing.JTextField();
        nomFamilia = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        tablaFamilia = new javax.swing.JTable();
        btnAfegirFamilia = new javax.swing.JButton();
        btnCercarTotsFamilia = new javax.swing.JButton();
        btnEliminarFamilia = new javax.swing.JButton();
        btnModificarFamilia = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        nomModul = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        idModul = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        tablaModul = new javax.swing.JTable();
        btnCercarTotsModul = new javax.swing.JButton();
        btnModificarModul = new javax.swing.JButton();
        btnEliminarModul = new javax.swing.JButton();
        btnAfegirModul = new javax.swing.JButton();
        cicloModulo = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nifAlumne = new javax.swing.JTextField();
        nomAlumne = new javax.swing.JTextField();
        cognomAlumne = new javax.swing.JTextField();
        correuAlumne = new javax.swing.JTextField();
        telefonAlumne = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAlumne = new javax.swing.JTable();
        btnCercarTotsAlumne = new javax.swing.JButton();
        btnCercarCognom = new javax.swing.JButton();
        bnCercarNifAlumne = new javax.swing.JButton();
        btnAfegirAlumne = new javax.swing.JButton();
        btnModificarAlumne = new javax.swing.JButton();
        btnEliminarAlumne = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jLabel6 = new javax.swing.JLabel();
        nomUF = new javax.swing.JTextField();
        idUF = new javax.swing.JTextField();
        horesUF = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableUF = new javax.swing.JTable();
        btnCercarTotsUF = new javax.swing.JButton();
        btnAfegirUF = new javax.swing.JButton();
        btnModificarUF = new javax.swing.JButton();
        btnEliminarUF = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        moduloUnitatFormativa = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cursUnitatFormativa = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        matriculaUnitatFormativa = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnCercarUFMatricula = new javax.swing.JButton();
        btnCercarNIFMatricula = new javax.swing.JButton();
        btnCercarCursMatricula = new javax.swing.JButton();
        btnCercarTotsMatricula = new javax.swing.JButton();
        btnCercarCicleMatricula = new javax.swing.JButton();
        btnAfegirMatricula = new javax.swing.JButton();
        btnCercarFamiliaMatricula = new javax.swing.JButton();
        btnModificarMatricula = new javax.swing.JButton();
        boxModalitatMatricula = new javax.swing.JComboBox<>();
        boxDescompteMatricula = new javax.swing.JComboBox<>();
        dataMatricula = new javax.swing.JTextField();
        alumneMatricula = new javax.swing.JTextField();
        idMatricula = new javax.swing.JTextField();
        btnEliminarMatricula = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableMatricula = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        boxModalitatMatricula1 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        boxModalitatMatricula2 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        boxModalitatMatricula3 = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel13.setText("ID");

        jLabel14.setText("Nom");

        jLabel15.setText("Grau");

        tableCicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tableCicle);

        idCicle.setEditable(false);

        btnAfegirCicle.setText("Afegir Cicle");
        btnAfegirCicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirCicleActionPerformed(evt);
            }
        });

        btnCercarTotsCicle.setText("Cercar Tots");
        btnCercarTotsCicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCercarTotsCicleActionPerformed(evt);
            }
        });

        btnModificarCicle.setText("Modificar Cicle");
        btnModificarCicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCicleActionPerformed(evt);
            }
        });

        btnEliminarCicle.setText("Eliminar Cicle");
        btnEliminarCicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCicleActionPerformed(evt);
            }
        });

        jLabel17.setText("Familia");

        grauCicle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medio", "Superior" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane6)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idCicle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(nomCicle, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(familiaCicle, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17)
                            .addComponent(grauCicle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificarCicle, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAfegirCicle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminarCicle, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCercarTotsCicle, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(134, 134, 134))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idCicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAfegirCicle)
                    .addComponent(btnCercarTotsCicle)
                    .addComponent(familiaCicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEliminarCicle)
                        .addComponent(btnModificarCicle))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomCicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(grauCicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(188, 188, 188)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cicle", jPanel3);

        jLabel18.setText("ID");

        jLabel19.setText("Nom");

        idCurs.setEditable(false);

        btnAfegirCurs.setText("Afegir Curs");
        btnAfegirCurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirCursActionPerformed(evt);
            }
        });

        btnCercarTotsCurs.setText("Cercar Tots");
        btnCercarTotsCurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCercarTotsCursActionPerformed(evt);
            }
        });

        btnEliminarCurs.setText("Eliminar Curs");
        btnEliminarCurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCursActionPerformed(evt);
            }
        });

        btnModificarCurs.setText("Modificar Curs");
        btnModificarCurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCursActionPerformed(evt);
            }
        });

        tablaCurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tablaCurs);

        nomCurs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PRIMER", "SEGON" }));

        jLabel28.setText("Cicle");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nomCurs, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idCurs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                            .addComponent(jLabel28))
                        .addGap(161, 161, 161)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAfegirCurs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarCurs, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnModificarCurs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCercarTotsCurs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(283, Short.MAX_VALUE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(cicleCurs, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idCurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAfegirCurs)
                        .addComponent(btnCercarTotsCurs)))
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminarCurs)
                            .addComponent(btnModificarCurs)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomCurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel28)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cicleCurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Curs", jPanel4);

        jLabel21.setText("ID");

        jLabel22.setText("Nom");

        idFamilia.setEditable(false);

        tablaFamilia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tablaFamilia);

        btnAfegirFamilia.setText("Afegir Familia");
        btnAfegirFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirFamiliaActionPerformed(evt);
            }
        });

        btnCercarTotsFamilia.setText("Cercar Tots");
        btnCercarTotsFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCercarTotsFamiliaActionPerformed(evt);
            }
        });

        btnEliminarFamilia.setText("Eliminar Familia");
        btnEliminarFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFamiliaActionPerformed(evt);
            }
        });

        btnModificarFamilia.setText("Modificar Familia");
        btnModificarFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarFamiliaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(idFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminarFamilia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAfegirFamilia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnModificarFamilia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCercarTotsFamilia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 315, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAfegirFamilia)
                    .addComponent(btnCercarTotsFamilia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addGap(16, 16, 16)
                .addComponent(nomFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarFamilia)
                    .addComponent(btnModificarFamilia))
                .addGap(120, 120, 120)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Familia", jPanel5);

        jLabel24.setText("Nom modul");

        jLabel29.setText("ID");

        idModul.setEditable(false);
        idModul.setFocusable(false);

        tablaModul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(tablaModul);

        btnCercarTotsModul.setText("Cercar Tots");
        btnCercarTotsModul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCercarTotsModulActionPerformed(evt);
            }
        });

        btnModificarModul.setText("Modificar Modul");
        btnModificarModul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarModulActionPerformed(evt);
            }
        });

        btnEliminarModul.setText("Eliminar Modul");
        btnEliminarModul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarModulActionPerformed(evt);
            }
        });

        btnAfegirModul.setText("Afegir Modul");
        btnAfegirModul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirModulActionPerformed(evt);
            }
        });

        jLabel30.setText("Ciclo");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cicloModulo)
                            .addComponent(jLabel24)
                            .addComponent(nomModul)
                            .addComponent(jLabel29)
                            .addComponent(idModul, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(306, 306, 306)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCercarTotsModul, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificarModul))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarModul, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAfegirModul, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(idModul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(nomModul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel30))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCercarTotsModul)
                            .addComponent(btnEliminarModul))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificarModul)
                            .addComponent(btnAfegirModul))))
                .addGap(18, 18, 18)
                .addComponent(cicloModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modul", jPanel7);

        jLabel1.setText("NIF");

        jLabel2.setText("Nom");

        jLabel3.setText("Cognom");

        jLabel4.setText("Correu");

        jLabel5.setText("Telefon");

        tableAlumne.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIF", "Nom", "Cognom", "Correu", "Telefon"
            }
        ));
        jScrollPane1.setViewportView(tableAlumne);

        btnCercarTotsAlumne.setText("Cercar Tots");
        btnCercarTotsAlumne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCercarTotsAlumneActionPerformed(evt);
            }
        });

        btnCercarCognom.setText("Cercar Cognom");
        btnCercarCognom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCercarCognomActionPerformed(evt);
            }
        });

        bnCercarNifAlumne.setText("Cercar NIF");
        bnCercarNifAlumne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnCercarNifAlumneActionPerformed(evt);
            }
        });

        btnAfegirAlumne.setText("Afegir Alumne");
        btnAfegirAlumne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirAlumneActionPerformed(evt);
            }
        });

        btnModificarAlumne.setText("Modificar Alumne");
        btnModificarAlumne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarAlumneActionPerformed(evt);
            }
        });

        btnEliminarAlumne.setText("Eliminar Alumne");
        btnEliminarAlumne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAlumneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(238, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(nomAlumne, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(cognomAlumne)
                            .addComponent(nifAlumne))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(correuAlumne, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(telefonAlumne))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnModificarAlumne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bnCercarNifAlumne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCercarTotsAlumne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCercarCognom, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(btnEliminarAlumne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAfegirAlumne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(190, 190, 190))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nifAlumne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(correuAlumne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCercarCognom)
                                .addComponent(bnCercarNifAlumne)))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomAlumne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefonAlumne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cognomAlumne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCercarTotsAlumne)
                            .addComponent(btnAfegirAlumne))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificarAlumne)
                            .addComponent(btnEliminarAlumne))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Alumne", jPanel2);

        label1.setText("ID");

        label2.setText("Nom");

        jLabel6.setText("Hores");

        idUF.setEditable(false);

        tableUF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nom", "Hores"
            }
        ));
        jScrollPane3.setViewportView(tableUF);

        btnCercarTotsUF.setText("Cercar Tots");
        btnCercarTotsUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCercarTotsUFActionPerformed(evt);
            }
        });

        btnAfegirUF.setText("Afegir UF");
        btnAfegirUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirUFActionPerformed(evt);
            }
        });

        btnModificarUF.setText("Modificar UF");
        btnModificarUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarUFActionPerformed(evt);
            }
        });

        btnEliminarUF.setText("Eliminar per nom");
        btnEliminarUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUFActionPerformed(evt);
            }
        });

        jLabel16.setText("Modul");

        jLabel20.setText("Curs");

        jLabel23.setText("Matricula");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cursUnitatFormativa, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nomUF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(idUF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                            .addComponent(jLabel20))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel6)
                            .addComponent(jLabel16)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(matriculaUnitatFormativa, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(moduloUnitatFormativa, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(horesUF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                                .addGap(74, 74, 74)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCercarTotsUF)
                                    .addComponent(btnAfegirUF, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnModificarUF, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEliminarUF))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(6, 6, 6)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCercarTotsUF)
                    .addComponent(btnModificarUF)
                    .addComponent(horesUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(7, 7, 7)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moduloUnitatFormativa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAfegirUF)
                    .addComponent(btnEliminarUF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cursUnitatFormativa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matriculaUnitatFormativa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Unitat formativa", jPanel8);

        jLabel7.setText("ID");

        jLabel8.setText("NIF Alumne");

        jLabel9.setText("Curs");

        jLabel11.setText("Modalitat");

        jLabel12.setText("Descompte");

        btnCercarUFMatricula.setText("Cercar per UF");

        btnCercarNIFMatricula.setText("Cercar per NIF");

        btnCercarCursMatricula.setText("Cercar per Curs");

        btnCercarTotsMatricula.setText("Cercar Tots");

        btnCercarCicleMatricula.setText("Cercar per Cicle");

        btnAfegirMatricula.setText("Afergir Matricula");

        btnCercarFamiliaMatricula.setText("Cercar per Familia");

        btnModificarMatricula.setText("Modificar Matricula");

        boxModalitatMatricula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        boxDescompteMatricula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        idMatricula.setEditable(false);

        btnEliminarMatricula.setText("Eliminar Matricula");

        tableMatricula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tableMatricula);

        jLabel27.setText("Data");

        boxModalitatMatricula1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel25.setText("Cicle");

        boxModalitatMatricula2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel26.setText("Familia");

        boxModalitatMatricula3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(idMatricula)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dataMatricula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(alumneMatricula, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel27)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(boxModalitatMatricula3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminarMatricula)
                                .addGap(231, 231, 231))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel11)
                                            .addComponent(boxDescompteMatricula, 0, 100, Short.MAX_VALUE)
                                            .addComponent(jLabel12)
                                            .addComponent(boxModalitatMatricula, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(159, 159, 159)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCercarUFMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnCercarCursMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnCercarFamiliaMatricula)
                                            .addComponent(btnCercarCicleMatricula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btnCercarTotsMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAfegirMatricula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnModificarMatricula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnCercarNIFMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(149, 159, Short.MAX_VALUE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(boxModalitatMatricula1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boxModalitatMatricula2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxDescompteMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alumneMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxModalitatMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxModalitatMatricula3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCercarCursMatricula)
                            .addComponent(btnCercarNIFMatricula))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCercarUFMatricula)
                            .addComponent(btnCercarTotsMatricula))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCercarFamiliaMatricula)
                            .addComponent(btnAfegirMatricula))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCercarCicleMatricula)
                            .addComponent(btnModificarMatricula))
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarMatricula)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxModalitatMatricula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxModalitatMatricula2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Matricula", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAfegirAlumneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirAlumneActionPerformed
        String nif = nifAlumne.getText();
        String nom = nomAlumne.getText();
        String cognom = cognomAlumne.getText();
        String correu = correuAlumne.getText();
        String telefon = telefonAlumne.getText();
        Alumne_controller ac = new Alumne_controller();
        Alumne a = new Alumne(nif, nom, cognom, correu, telefon);
        ac.afegir(a);
        JOptionPane.showMessageDialog(this, "Inserció feta correctament");
    }//GEN-LAST:event_btnAfegirAlumneActionPerformed

    private void bnCercarNifAlumneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnCercarNifAlumneActionPerformed
        String nif = nifAlumne.getText();
        Alumne_controller ac = new Alumne_controller();
        Alumne a = ac.cercarNif(nif);
    }//GEN-LAST:event_bnCercarNifAlumneActionPerformed

    private void btnCercarCognomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCercarCognomActionPerformed
        List<Alumne> alumnes = new ArrayList();
        String cognom = cognomAlumne.getText();
        Alumne_controller ac = new Alumne_controller();
        alumnes = ac.cercarCognom(cognom);
        for (int i = 0; i < alumnes.size(); i++) {
            tableAlumne.getModel().setValueAt(alumnes.get(i).getNif(), i, 0);
            tableAlumne.getModel().setValueAt(alumnes.get(i).getNom(), i, 1);
            tableAlumne.getModel().setValueAt(alumnes.get(i).getCognom(), i, 2);
            tableAlumne.getModel().setValueAt(alumnes.get(i).getCorreu(), i, 3);
            tableAlumne.getModel().setValueAt(alumnes.get(i).getTelefon(), i, 4);
        }
    }//GEN-LAST:event_btnCercarCognomActionPerformed

    private void btnCercarTotsAlumneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCercarTotsAlumneActionPerformed
        List<Alumne> alumnes = new ArrayList();
        Alumne_controller ac = new Alumne_controller();
        alumnes = ac.cercarTots();
        for (int i = 0; i < alumnes.size(); i++) {
            tableAlumne.getModel().setValueAt(alumnes.get(i).getNif(), i, 0);
            tableAlumne.getModel().setValueAt(alumnes.get(i).getNom(), i, 1);
            tableAlumne.getModel().setValueAt(alumnes.get(i).getCognom(), i, 2);
            tableAlumne.getModel().setValueAt(alumnes.get(i).getCorreu(), i, 3);
            tableAlumne.getModel().setValueAt(alumnes.get(i).getTelefon(), i, 4);
        }
    }//GEN-LAST:event_btnCercarTotsAlumneActionPerformed

    private void btnModificarAlumneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarAlumneActionPerformed
        String nif = nifAlumne.getText();
        String nom = nomAlumne.getText();
        String cognom = cognomAlumne.getText();
        String correu = correuAlumne.getText();
        String telefon = telefonAlumne.getText();
        Alumne_controller ac = new Alumne_controller();
        Alumne a = ac.cercarNif(nif);
        a.setNom(nom);
        a.setCognom(cognom);
        a.setCorreu(correu);
        a.setTelefon(telefon);
        ac.modificar(a);
        JOptionPane.showMessageDialog(this, "Modificació feta correctament");
    }//GEN-LAST:event_btnModificarAlumneActionPerformed

    private void btnEliminarAlumneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAlumneActionPerformed
        String nif = nifAlumne.getText();
        Alumne_controller ac = new Alumne_controller();
        Alumne a = ac.cercarNif(nif);
        ac.eliminar(a);
        JOptionPane.showMessageDialog(this, "Eliminació feta correctament");
    }//GEN-LAST:event_btnEliminarAlumneActionPerformed

    private void btnAfegirUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirUFActionPerformed
//        String nomuf = nomUF.getText();
//        try {
//            Curs curs;
//            Curs_Controller cc = new Curs_Controller();
//            int hores = Integer.parseInt(horesUF.getText());
//            Long idC = Long.parseLong(cursUnitatFormativa.getText());
//            curs = cc.cercarPerId(idC);
//            JOptionPane.showMessageDialog(this, curs);
//            uf = new UnitatFormativa(nomuf, hores, curs);
//            ufc = new UnitatFormativa_controller();
//            if (ufc.afegir(uf)) {
//                JOptionPane.showMessageDialog(this, "Registre afegit");
//            } else {
//                JOptionPane.showMessageDialog(this, "Error al afegir");
//            }
//        } catch (NumberFormatException ex) {
//            JOptionPane.showMessageDialog(this, "El nombre d'hores ha de ser numeric");
//        } catch (PersistenceException ex) {
//            JOptionPane.showMessageDialog(this, "Error. Element duplicat");
//        }
    }//GEN-LAST:event_btnAfegirUFActionPerformed

    private void btnEliminarUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUFActionPerformed
//        try {
//            String nomuf = nomUF.getText();
//            ufc = new UnitatFormativa_controller();
//            UnitatFormativa uf = ufc.cercarUF(nomuf);
//            if (ufc.eliminar(uf) == true) {
//                JOptionPane.showMessageDialog(this, "Registre eliminat");
//            } else {
//                JOptionPane.showMessageDialog(this, "Error al eliminar");
//            }
//        } catch (NoResultException ex) {
//            JOptionPane.showMessageDialog(this, "No s'ha trobat objecte a eliminar");
//        }
    }//GEN-LAST:event_btnEliminarUFActionPerformed

    private void btnModificarUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUFActionPerformed
//        String nomuf = nomUF.getText();
//        ufc = new UnitatFormativa_controller();
//        UnitatFormativa uf = ufc.cercarUF(nomuf);
//        uf.setHores(Integer.parseInt(horesUF.getText()));
//        uf.setNom(nomuf);
//        if (ufc.modificar(uf) == true) {
//            JOptionPane.showMessageDialog(this, "Modificació correcta");
//        } else {
//            JOptionPane.showMessageDialog(this, "Error al inserir");
//        }
    }//GEN-LAST:event_btnModificarUFActionPerformed

    private void btnCercarTotsUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCercarTotsUFActionPerformed
//        try {
//            ufc = new UnitatFormativa_controller();
//            List<UnitatFormativa> ConsultaTots = ufc.cercarTots();
//            String col[] = {"Id", "Nom", "Hores"};
//            DefaultTableModel tableModel = new DefaultTableModel(col, 0);
//            for (UnitatFormativa uf : ConsultaTots) {
//                System.out.println("Trobat");
//                Object[] data = {
//                    uf.getId(),
//                    uf.getNom(),
//                    uf.getHores()
//                };
//                tableModel.addRow(data);
//            }
//            tableUF.setModel(tableModel);
//            if (ConsultaTots.isEmpty()) {
//                JOptionPane.showMessageDialog(this, "Sense resultats");
//            }
//        } catch (PersistenceException ex) {
//            JOptionPane.showMessageDialog(this, "Error al recuperar les dades");
//        }
    }//GEN-LAST:event_btnCercarTotsUFActionPerformed

    private void btnAfegirCursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirCursActionPerformed
        Nom nom;
        Curs_Controller cursc = new Curs_Controller();
        if (nomCurs.getSelectedItem().toString().equals("PRIMER")) {
            nom = Curs.Nom.PRIMER;
        } else {
            nom = Curs.Nom.SEGON;
        }
        Long idCicle = Long.parseLong(cicleCurs.getText());
        Cicle_controller cc = new Cicle_controller();
        Cicle c = cc.cercarCicleId(idCicle);
        Curs curs = new Curs(nom, c);
        if (cursc.afegir(curs)) {
            JOptionPane.showMessageDialog(this, "Afegit");
        } else {
            JOptionPane.showMessageDialog(this, "Error al inserir les dades");
        }
    }//GEN-LAST:event_btnAfegirCursActionPerformed

    private void btnCercarTotsCursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCercarTotsCursActionPerformed
        List<Curs> cursos = new ArrayList();
        Curs_Controller cursc = new Curs_Controller();
        cursos = cursc.cercarTots();
        for (int i = 0; i < cursos.size(); i++) {
            tablaCurs.getModel().setValueAt(cursos.get(i).getId(), i, 0);
            tablaCurs.getModel().setValueAt(cursos.get(i).getNom(), i, 1);
            tablaCurs.getModel().setValueAt(cursos.get(i).getCicleCurs().getNom(), i, 2);
        }
    }//GEN-LAST:event_btnCercarTotsCursActionPerformed

    private void btnAfegirModulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirModulActionPerformed
        Modul_controller mc = new Modul_controller();
        String nombre = nomModul.getText();
        Long idCicle = Long.parseLong(cicloModulo.getText());
        Cicle_controller cc = new Cicle_controller();
        Cicle c = cc.cercarCicleId(idCicle);
        Modul modul = new Modul(nombre, c);
        if (mc.afegir(modul)) {
            JOptionPane.showMessageDialog(this, "Afegit");
        } else {
            JOptionPane.showMessageDialog(this, "Error al inserir les dades");
        }
    }//GEN-LAST:event_btnAfegirModulActionPerformed

    private void btnAfegirFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirFamiliaActionPerformed
        String nom = nomFamilia.getText();
        Familia_controller fc = new Familia_controller();
        Familia f = new Familia(nom);
        if (fc.afegir(f)) {
            JOptionPane.showMessageDialog(this, "Afegit");
        } else {
            JOptionPane.showMessageDialog(this, "Error al inserir les dades");
        }
    }//GEN-LAST:event_btnAfegirFamiliaActionPerformed

    private void btnCercarTotsFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCercarTotsFamiliaActionPerformed
        List<Familia> familias = new ArrayList();
        Familia_controller fc = new Familia_controller();
        familias = fc.cercarTots();
        for (int i = 0; i < familias.size(); i++) {
            tablaFamilia.getModel().setValueAt(familias.get(i).getIdFamilia(), i, 0);
            tablaFamilia.getModel().setValueAt(familias.get(i).getNom(), i, 1);
        }
    }//GEN-LAST:event_btnCercarTotsFamiliaActionPerformed

    private void btnModificarFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarFamiliaActionPerformed
        String nuevoNombre = JOptionPane.showInputDialog(this, "Inserta el nuevo nombre");
        String nom = nomFamilia.getText();
        Familia_controller fc = new Familia_controller();
        Familia f;
        f = fc.cercarFamilia(nom);
        f.setNom(nuevoNombre);
        if (fc.modificar(f)) {
            JOptionPane.showMessageDialog(this, "Modificat");
        } else {
            JOptionPane.showMessageDialog(this, "Error al modificar les dades");
        }

    }//GEN-LAST:event_btnModificarFamiliaActionPerformed

    private void btnEliminarFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFamiliaActionPerformed
        try {
            String nom = nomFamilia.getText();
            Familia_controller fc = new Familia_controller();
            Familia f;
            f = fc.cercarFamilia(nom);
            if (fc.eliminar(f)) {
                JOptionPane.showMessageDialog(this, "Registre eliminat");
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar");
            }
        } catch (NoResultException ex) {
            JOptionPane.showMessageDialog(this, "No s'ha trobat objecte a eliminar");
        }
    }//GEN-LAST:event_btnEliminarFamiliaActionPerformed

    private void btnAfegirCicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirCicleActionPerformed
        String nom = nomCicle.getText();
        Long idFamilia = Long.parseLong(familiaCicle.getText());
        String grau = (String) grauCicle.getSelectedItem();
        Familia_controller fc = new Familia_controller();
        Familia f = fc.cercarFamiliaId(idFamilia);
        Cicle_controller cc = new Cicle_controller();
        Cicle c = new Cicle(nom, grau, f);
        if (cc.afegir(c)) {
            JOptionPane.showMessageDialog(this, "Afegit");
        } else {
            JOptionPane.showMessageDialog(this, "Error al inserir les dades");
        }
    }//GEN-LAST:event_btnAfegirCicleActionPerformed

    private void btnCercarTotsCicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCercarTotsCicleActionPerformed
        List<Cicle> ciclos = new ArrayList();
        Cicle_controller cc = new Cicle_controller();
        ciclos = cc.cercarTots();
        for (int i = 0; i < ciclos.size(); i++) {
            tableCicle.getModel().setValueAt(ciclos.get(i).getNom(), i, 0);
            tableCicle.getModel().setValueAt(ciclos.get(i).getGrau(), i, 1);
            tableCicle.getModel().setValueAt(ciclos.get(i).getFamilia().getNom(), i, 2);

        }
    }//GEN-LAST:event_btnCercarTotsCicleActionPerformed

    private void btnModificarCicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCicleActionPerformed
        String nuevoNombre = JOptionPane.showInputDialog(this, "Inserta el nuevo nombre");
        String nom = nomCicle.getText();
        Long idFamilia = Long.parseLong(familiaCicle.getText());
        String grau = (String) grauCicle.getSelectedItem();
        Familia_controller fc = new Familia_controller();
        Familia f = fc.cercarFamiliaId(idFamilia);
        Cicle_controller cc = new Cicle_controller();
        Cicle c = cc.cercarCicle(nom);
        c.setNom(nuevoNombre);
        c.setGrau(grau);
        c.setFamilia(f);
        cc.modificar(c);
    }//GEN-LAST:event_btnModificarCicleActionPerformed

    private void btnEliminarCicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCicleActionPerformed
        try {
            String nom = nomCicle.getText();
            Cicle_controller cc = new Cicle_controller();
            Cicle c;
            c = cc.cercarCicle(nom);
            if (cc.eliminar(c)) {
                JOptionPane.showMessageDialog(this, "Registre eliminat");
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar");
            }
        } catch (NoResultException ex) {
            JOptionPane.showMessageDialog(this, "No s'ha trobat objecte a eliminar");
        }
    }//GEN-LAST:event_btnEliminarCicleActionPerformed

    private void btnEliminarCursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCursActionPerformed
        String nuevaId = JOptionPane.showInputDialog(this, "Inserta la id de curso a buscar");
        Curs_Controller cursc = new Curs_Controller();
        Curs curso = cursc.cercarPerId(Long.parseLong(nuevaId));
        if (cursc.eliminar(curso)) {
            JOptionPane.showMessageDialog(this, "Registre eliminat");
        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar");
        }
    }//GEN-LAST:event_btnEliminarCursActionPerformed

    private void btnModificarCursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCursActionPerformed
        String nuevaId = JOptionPane.showInputDialog(this, "Inserta la id de curso a buscar");
        Long idCicle = Long.parseLong(cicleCurs.getText());
        Nom nom;
        Cicle_controller cc = new Cicle_controller();
        Curs_Controller cursc = new Curs_Controller();
        Curs curso = cursc.cercarPerId(Long.parseLong(nuevaId));
        Cicle ciclo = cc.cercarCicleId(idCicle);
        if (nomCurs.getSelectedItem().toString().equals("PRIMER")) {
            nom = Curs.Nom.PRIMER;
        } else {
            nom = Curs.Nom.SEGON;
        }
        curso.setNom(nom);
        curso.setCicleCurs(ciclo);

        if (cursc.modificar(curso)) {
            JOptionPane.showMessageDialog(this, "Registre modificat");
        } else {
            JOptionPane.showMessageDialog(this, "Error al modificar");
        }
    }//GEN-LAST:event_btnModificarCursActionPerformed

    private void btnModificarModulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarModulActionPerformed
        String nuevoNombre = JOptionPane.showInputDialog(this, "Inserta un nuevo nombre");
        String nom = nomModul.getText();
        Long idCicle = Long.parseLong(cicloModulo.getText());
        Modul_controller mc = new Modul_controller();
        Modul m = mc.cercarModul(nom);
        m.setNom(nuevoNombre);
        Cicle_controller cc = new Cicle_controller();
        Cicle c = cc.cercarCicleId(idCicle);
        m.setCicleModul(c);
        if (mc.modificar(m)) {
            JOptionPane.showMessageDialog(this, "Registre modificat");
        } else {
            JOptionPane.showMessageDialog(this, "Error al modificar");
        }
    }//GEN-LAST:event_btnModificarModulActionPerformed

    private void btnCercarTotsModulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCercarTotsModulActionPerformed
        List<Modul> modulos = new ArrayList();
        Modul_controller mc = new Modul_controller();
        modulos = mc.cercarTots();
        for (int i = 0; i < modulos.size(); i++) {
            tablaModul.getModel().setValueAt(modulos.get(i).getId(), i, 0);
            tablaModul.getModel().setValueAt(modulos.get(i).getNom(), i, 1);
            tablaModul.getModel().setValueAt(modulos.get(i).getCicleModul().getNom(), i, 2);
        }
    }//GEN-LAST:event_btnCercarTotsModulActionPerformed

    private void btnEliminarModulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarModulActionPerformed
        String nom = nomModul.getText();
        Modul_controller mc = new Modul_controller();
        Modul m = mc.cercarModul(nom);
        if (mc.eliminar(m)) {
            JOptionPane.showMessageDialog(this, "Registre eliminat");
        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar");
        }
    }//GEN-LAST:event_btnEliminarModulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alumneMatricula;
    private javax.swing.JButton bnCercarNifAlumne;
    private javax.swing.JComboBox<String> boxDescompteMatricula;
    private javax.swing.JComboBox<String> boxModalitatMatricula;
    private javax.swing.JComboBox<String> boxModalitatMatricula1;
    private javax.swing.JComboBox<String> boxModalitatMatricula2;
    private javax.swing.JComboBox<String> boxModalitatMatricula3;
    private javax.swing.JButton btnAfegirAlumne;
    private javax.swing.JButton btnAfegirCicle;
    private javax.swing.JButton btnAfegirCurs;
    private javax.swing.JButton btnAfegirFamilia;
    private javax.swing.JButton btnAfegirMatricula;
    private javax.swing.JButton btnAfegirModul;
    private javax.swing.JButton btnAfegirUF;
    private javax.swing.JButton btnCercarCicleMatricula;
    private javax.swing.JButton btnCercarCognom;
    private javax.swing.JButton btnCercarCursMatricula;
    private javax.swing.JButton btnCercarFamiliaMatricula;
    private javax.swing.JButton btnCercarNIFMatricula;
    private javax.swing.JButton btnCercarTotsAlumne;
    private javax.swing.JButton btnCercarTotsCicle;
    private javax.swing.JButton btnCercarTotsCurs;
    private javax.swing.JButton btnCercarTotsFamilia;
    private javax.swing.JButton btnCercarTotsMatricula;
    private javax.swing.JButton btnCercarTotsModul;
    private javax.swing.JButton btnCercarTotsUF;
    private javax.swing.JButton btnCercarUFMatricula;
    private javax.swing.JButton btnEliminarAlumne;
    private javax.swing.JButton btnEliminarCicle;
    private javax.swing.JButton btnEliminarCurs;
    private javax.swing.JButton btnEliminarFamilia;
    private javax.swing.JButton btnEliminarMatricula;
    private javax.swing.JButton btnEliminarModul;
    private javax.swing.JButton btnEliminarUF;
    private javax.swing.JButton btnModificarAlumne;
    private javax.swing.JButton btnModificarCicle;
    private javax.swing.JButton btnModificarCurs;
    private javax.swing.JButton btnModificarFamilia;
    private javax.swing.JButton btnModificarMatricula;
    private javax.swing.JButton btnModificarModul;
    private javax.swing.JButton btnModificarUF;
    private javax.swing.JTextField cicleCurs;
    private javax.swing.JTextField cicloModulo;
    private javax.swing.JTextField cognomAlumne;
    private javax.swing.JTextField correuAlumne;
    private javax.swing.JTextField cursUnitatFormativa;
    private javax.swing.JTextField dataMatricula;
    private javax.swing.JTextField familiaCicle;
    private javax.swing.JComboBox<String> grauCicle;
    private javax.swing.JTextField horesUF;
    private javax.swing.JTextField idCicle;
    private javax.swing.JTextField idCurs;
    private javax.swing.JTextField idFamilia;
    private javax.swing.JTextField idMatricula;
    private javax.swing.JTextField idModul;
    private javax.swing.JTextField idUF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JTextField matriculaUnitatFormativa;
    private javax.swing.JTextField moduloUnitatFormativa;
    private javax.swing.JTextField nifAlumne;
    private javax.swing.JTextField nomAlumne;
    private javax.swing.JTextField nomCicle;
    private javax.swing.JComboBox nomCurs;
    private javax.swing.JTextField nomFamilia;
    private javax.swing.JTextField nomModul;
    private javax.swing.JTextField nomUF;
    private javax.swing.JTable tablaCurs;
    private javax.swing.JTable tablaFamilia;
    private javax.swing.JTable tablaModul;
    private javax.swing.JTable tableAlumne;
    private javax.swing.JTable tableCicle;
    private javax.swing.JTable tableMatricula;
    private javax.swing.JTable tableUF;
    private javax.swing.JTextField telefonAlumne;
    // End of variables declaration//GEN-END:variables
}
